### ISSUE TITLE
Don't Work at all

### ISSUE THREAD

**Issue by cotocisternas** [ereslibre/realtime-validations#1]
Dont generate the "realtime_validations.js", just a "realtime_validations.custom.js" commented... don't work at all.. do u have a demo or something?

Ej:

rails g realtime_validations:install
      create  config/initializers/realtime_validations_initializer.rb
      create  app/assets/javascripts/realtime_validations.custom.js

Ty.

**Comment by ereslibre** [comment]
You don't need a 'realtime_validations.js', what is generated is a 'realtime_validations.custom.js' in purpose, that will contain commented code, because it is not 'required'. realtime-validations gem can work on the client side with this code commented out, but is nice to have it as a generator just to let the user know that he/she is able to configure it even further.

I am writing in other repository some usage examples, because it is a work in progress right now. A first look: 'customFields' allows you to send to the ValidationsController more fields that it will need in order to identify the current user, client, session or whatever you need. 'showErrors' is the function that is called when the field 'field' has some errors 'errors. In the same sense, 'hideErrors' is called when the field 'field' is validated correctly and has no errors.

All functions have defined a default function that will work out of the box, and for this reason it is not mandatory for you to write them, but you will need to do so if you want a higher level of customization.
